version: '3.9'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:14.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=poll_admin
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=poll_db
volumes:
  postgres_data:

#version: "3.9"  # optional since v1.27.0
#services:
#  poll1:
#    build: .
#    #image: poll
#    ports:
#      - "8000:8000"
#    volumes:
#      - db_poll:/usr/src/app/db
#    restart: always
#volumes:
#  db_poll: